# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Northeast Cuisine
tagline:          'A repository of Visualizations for Northeast Cuisine'
description:      'A repository of Visualizations for Northeast Cuisine'
url:              https://necuisineus.github.io/
baseurl:          https://necuisineus.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
